import requests
import re
import time
import random
from datetime import datetime

def fetch_srvid(package, caids):
    url = f"https://en.kingofsat.net/pack-{package.lower()}.php"
    
    # قائمة بمتصفحات مختلفة لتبديل الهوية (User-Agent Rotation)
    user_agents = [
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36',
        'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'
    ]

    headers = {
        'User-Agent': random.choice(user_agents),
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
        'Accept-Language': 'en-US,en;q=0.5',
        'Connection': 'keep-alive',
        'Upgrade-Insecure-Requests': '1',
        'Referer': 'https://en.kingofsat.net/packages.php'
    }
    
    print(f"-> Scanning: {package.upper()}...")
    
    try:
        # إضافة وقت انتظار عشوائي بين الطلبات لتجنب الحظر
        time.sleep(random.uniform(2, 5))
        
        response = requests.get(url, headers=headers, timeout=30)
        
        if response.status_code == 200:
            # استخدام Regex يبحث عن الأنماط داخل كود الصفحة بأكمله (حتى لو تغيرت الـ classes)
            # نبحث عن الـ SID الموجود في روابط الـ zapper أو الـ class الخاص به
            sids = re.findall(r'class="s">(\d+)<', response.text)
            names = re.findall(r'class="A3">([^<]+)<', response.text)
            
            if not sids:
                # محاولة بديلة إذا تغيرت أسماء الـ classes
                sids = re.findall(r'pos=(\d+)', response.text)

            output = []
            for i in range(min(len(sids), len(names))):
                sid_hex = "{:04X}".format(int(sids[i]))
                # تنظيف اسم القناة من أي رموز غريبة
                clean_name = names[i].strip().replace('|', '-')
                output.append(f"{caids}:{sid_hex}|{package.upper()}|{clean_name}")
            
            print(f"   Found: {len(output)} channels")
            return output
        else:
            print(f"   !! Access Denied (Status {response.status_code})")
            return []
    except Exception as e:
        print(f"   !! Error: {e}")
        return []

# القائمة الأساسية
packages = [
    ("bein", "0500"), ("osn", "0604"), ("art", "0604"),
    ("skygermany", "098D,09C4"), ("skyitalia", "0919,093B,09CD"),
    ("tivusat", "183D,183E"), ("skylink", "0624,0D96"),
    ("polsat", "1803,1861"), ("bis", "0500")
]

final_data = []
for pkg, caid in packages:
    res = fetch_srvid(pkg, caid)
    if res:
        final_data.extend(res)

header = f"#################################################################################\n"
header += f"### OSCam SRVID Generated by GitHub Action\n"
header += f"### Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}\n"
header += f"#################################################################################\n\n"

if final_data:
    with open("oscam.srvid", "w", encoding="utf-8") as f:
        f.write(header + "\n".join(final_data))
    print(f"\nSUCCESS: Created oscam.srvid with {len(final_data)} channels.")
else:
    # إنشاء ملف يوضح فشل السحب لتجنب توقف الأكشن
    with open("oscam.srvid", "w") as f:
        f.write(header + "# No data captured. Possible site block.")
    print("\nFAILED: No data found.")
