import requests
import re
import time
import random
from datetime import datetime
import urllib3

# تعطيل تحذيرات SSL
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

def fetch_srvid(session, package, caids):
    url = f"https://en.kingofsat.net/pack-{package.lower()}.php"
    
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
        'Accept-Language': 'en-US,en;q=0.5',
        'Referer': 'https://en.kingofsat.net/',
        'DNT': '1',
        'Connection': 'keep-alive',
    }
    
    print(f"-> Processing: {package.upper()}...")
    
    try:
        # وقت انتظار أطول قليلاً بين الطلبات
        time.sleep(random.uniform(3, 7))
        
        # استخدام Session للحفاظ على الكوكيز
        response = session.get(url, headers=headers, timeout=30, verify=False)
        
        if response.status_code == 200:
            # البحث عن الـ SID والأسماء (تحديث الـ Regex ليكون أكثر مرونة)
            sids = re.findall(r'class="s">(\d+)<', response.text)
            names = re.findall(r'class="A3">([^<]+)<', response.text)
            
            output = []
            if sids and names:
                for i in range(min(len(sids), len(names))):
                    sid_hex = "{:04X}".format(int(sids[i]))
                    output.append(f"{caids}:{sid_hex}|{package.upper()}|{names[i].strip()}")
                print(f"   Done: {len(output)} channels found.")
            else:
                print(f"   !! No patterns matched in HTML.")
            return output
        else:
            print(f"   !! Site blocked us. Status: {response.status_code}")
            return []
    except Exception as e:
        print(f"   !! Error: {e}")
        return []

# إنشاء Session واحدة لكل الطلبات
session = requests.Session()

# القائمة الأساسية (جرب باقتين بس في الأول عشان تتأكد)
packages = [
    ("bein", "0500"), ("osn", "0604"), ("art", "0604"),
    ("skygermany", "098D,09C4"), ("skyitalia", "0919,093B,09CD")
]

final_data = []
for pkg, caid in packages:
    res = fetch_srvid(session, pkg, caid)
    if res:
        final_data.extend(res)

header = f"#################################################################################\n"
header += f"### OSCam SRVID Generated by GitHub Action (Python Session Mode)\n"
header += f"### Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}\n"
header += f"#################################################################################\n\n"

if final_data:
    with open("oscam.srvid", "w", encoding="utf-8") as f:
        f.write(header + "\n".join(final_data))
    print(f"\nSUCCESS: Created oscam.srvid with {len(final_data)} channels.")
else:
    with open("oscam.srvid", "w") as f:
        f.write(header + "# No data captured. Site is blocking GitHub IP range.")
    print("\nFAILED: Site is still blocking the requests.")
