name: Generate OSCam SRVID

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl grep sed

      - name: Run Generator Script
        run: |
          # البحث عن المجلد الذي يحتوي على السكربت والدخول إليه
          cd $(find . -name "oscam-srvid-generator-kingofsat.sh" -exec dirname {} \;)
          chmod +x oscam-srvid-generator-kingofsat.sh
          ./oscam-srvid-generator-kingofsat.sh

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add **/*.srvid
          git commit -m "Update oscam.srvid $(date)" || exit 0
          git push
